var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
var ThContainer = styled.th(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  background-color: white;\n  position: sticky;\n  top: 0;\n  font-size: 18px;\n  display: flex;\n  align-items: center;\n  user-select: none;\n  align-self: flex-start;\n\n  .info {\n    cursor: pointer;\n    display: flex;\n    align-items: center;\n    gap: 0.5rem;\n    flex: 1;\n    width: 100%;\n\n    .sort {\n      background-color: transparent;\n      border: none;\n    }\n  }\n\n  .filter {\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    cursor: pointer;\n    opacity: 0;\n    transition: all 0.2s ease-in-out;\n  }\n\n  &:hover {\n    .filter {\n      opacity: 1;\n    }\n  }\n"], ["\n  background-color: white;\n  position: sticky;\n  top: 0;\n  font-size: 18px;\n  display: flex;\n  align-items: center;\n  user-select: none;\n  align-self: flex-start;\n\n  .info {\n    cursor: pointer;\n    display: flex;\n    align-items: center;\n    gap: 0.5rem;\n    flex: 1;\n    width: 100%;\n\n    .sort {\n      background-color: transparent;\n      border: none;\n    }\n  }\n\n  .filter {\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    cursor: pointer;\n    opacity: 0;\n    transition: all 0.2s ease-in-out;\n  }\n\n  &:hover {\n    .filter {\n      opacity: 1;\n    }\n  }\n"])));
export var ResizeBar = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  display: block;\n  position: absolute;\n  cursor: ", ";\n  width: 7px;\n  height: 50%;\n  right: 0px;\n  top: 50%;\n  transform: translateY(-50%);\n  z-index: 1;\n  border-right: 1px solid transparent;\n  border-color: #ccc;\n"], ["\n  display: block;\n  position: absolute;\n  cursor: ", ";\n  width: 7px;\n  height: 50%;\n  right: 0px;\n  top: 50%;\n  transform: translateY(-50%);\n  z-index: 1;\n  border-right: 1px solid transparent;\n  border-color: #ccc;\n"])), function (_a) {
    var resizable = _a.resizable;
    return (resizable ? "col-resize" : "default");
});
export default ThContainer;
var templateObject_1, templateObject_2;
//# sourceMappingURL=ColumnItem.styles.js.map